Toqozz/wired-notify

src/bus/receiver.rs
src/management/mod.rs

I'm using `i3wm` as a window manager and had a bug where `self_anchor` of a root block behaved as if it's `TL` regardless of its actual value. This change fixes the bug. I also tested it with another window manager (`marco`) and it doesn't seem to break anything.
I'm not sure I fixed the correct root cause though, since I still don't get what caused the bug. It makes sense to me that all anchors would behave like `TL` when `self_rect` size is zero, but it only happened in some WMs and I don't know why.
---
I also filled out server information. Cargo environmental variables seem reasonable to me. Some programs use these to decide the content of notifications (In my case it was Telegram not sending icons).

Fix a buggy interaction with i3wm; Fill out server information

---

src/cli.rs

A `--version` is missing, so I just added it.

add support for version printing

---

src/config.rs
src/manager.rs

Exactly like it sounds.
Added it because buttons now can be just buttons, with a click to deny/accept something, for example.
It will make easier for scripts I think for people in the future whose functionality deems cool :)

Add `interact_and_close` for notification config.

---

installer.sh

A bash script has been added that fixes dependency errors and provides an automated way to compile Wired Notify on RHEL-based systems that use DNF as the default package manager.

Wired Notify installation automation script

---

installer.sh

Hello!
I recently updated the installer code. The improvements I made were:
- I removed a double clone from the repository which, frankly, was there without any sense. Now it runs the build directly from the folder containing the installer.
- I added an update for Rust. This is because in previous versions of Fedora the Cargo compiler was throwing a compile-time incompatibility error.
- I added a process death for the Dunst program. This is because it was successfully uninstalled, but the remnants of Dunst were still running even after uninstallation.
- I removed the Git installation check. This because its presence is not necessary, as I removed the double clone from the repository.
And that's it, cheers!

Installer code updated

---

aur/wired-git/PKGBUILD

This fixes the source in the wired-git AUR package, which was invalid due to some changes on github's side.
closes #64

fix source in wired-git AUR package

---

README.md

1. systemd is not a command
2. enable is not a flag in systemctl, it's a subcommand

Correct the systemctl command in README.md

---

src/rendering/blocks/image_block.rs

cargo build output:
```rust
warning: use of deprecated associated function `image::DynamicImage::to_bgra`: replaced by `to_bgra8`
--> src/rendering/blocks/image_block.rs:137:26
|
137 |                         .to_bgra() // Cairo reads pixels back-to-front, so ARgb32 is actually BgrA32.
|                          ^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
```

Fix deprecated associated function

---

.github/workflows/build.yml
aur/wired-bin/PKGBUILD

* Closes #77 
Before adding the package to AUR, you must release a new version (0.10.3) to build the binary, comments welcome!

AUR: add wired-bin

---

src/config.rs
src/manager.rs
src/maths_utility.rs

- relates to https://github.com/Toqozz/wired-notify/issues/47
- slow down period of monitor and idle dirtiness check from 0.33sec to 1.0sec when no layouts require automatic selection of output monitor
- don't check mouse position or keyboard focus at all when no layouts require automatic selection of output monitor
- this is a stepping stone to unlocking wayland functionality without requiring us to fix everything all at once

fix: only get active monitor when necessary

---

rust-toolchain.toml
src/bus/dbus.rs
src/bus/dbus_codegen.rs
src/cli.rs
src/config.rs
src/manager.rs
src/maths_utility.rs
src/rendering/blocks/image_block.rs
src/rendering/layout.rs
src/rendering/window.rs

- I ran `cargo clippy --all -- -D clippy::all` and fixed all of the warnings
- I decided not to make this part of the GitHub workflow just yet, as my previous addition (mandatory `cargo fmt`) caused some toil for @Toqozz and I'd like to earn back some trust first :)
- I did manually test this with some notifications with and without icons, nothing seemed to explode :)

chore: set toolchain, fix warnings

---

README.md

The 'homeManagerConfiguration' arguments
- 'configuration'
- 'username'
- 'homeDirectory'
- 'stateVersion'
- 'extraModules'
- 'system'
have been removed. Instead use the arguments 'pkgs' and
'modules'. See the 22.11 release notes for more.

doc: fix home-manager example

---

README.md
flake.nix
home-manager.nix

I changed the URL literal to a string according to the [45 RFC](https://github.com/NixOS/rfcs/blob/master/rfcs/0045-deprecate-url-syntax.md)
Also removed unused variable `std`

nix: use string instead of url literal

---

README.md
wired.service

With the `wired.service` I had issues, that it would not start automatically on login to the session.
This PR changes the install target, as well as the starting condition so it hopefully gets started on any system.
I am not an expert in systemd, so if there is still improvement I am happy to adopt any suggestion.
Also added a little bit of info to the unit file and updated the `README.md`

Improve systemd service

---

flake.lock
flake.nix

- updated `nixpkgs` version in the flake lock file.
- fixed error: 'pkgconfig' has been renamed to/replaced by 'pkg-config'

nix: fix build on latest nixpkgs

---

src/rendering/layout.rs

Due to the split of negative render criterions as a separate configuration value (`render_criterions` and `render_anti_criterions`), there are some combinations of expressions that cannot be represented.
One example is `Or(AppImage, Not(AppName(""), AppName("notify-send"))`, i.e. render if there is an app image or an app name that isn't one of those specified. This useful because it allows me to introduce a top bar that is only present if necessary, but cannot be represented currently because both `render_criterions` and `render_anti_criterions` would require a `Not(x)`.
This tiny PR adds this simple expression and thus allows representation of any propositional logic formula. This also technically removes the need for render_anti_criterions, because everything can be written as a render …

feat: add `Not(criterion)` render criterion to allow for more complex logic

---

README.md

As explained [here](https://github.com/Toqozz/wired-notify/issues/115#issuecomment-1743992531) the explanation in the README is fixed

fix explanation from readme

---

.github/workflows/update-flake-lock.yml
default.nix
flake.lock
flake.nix
home-manager.nix
shell.nix
src/config.rs
src/main.rs

this makes the flake.nix file a bit more readable in my opinion :)
The changes are:
- Replacing `flake-utils` with [`flake-parts`] because [`flake-parts`] is "syntax-friendlier"
- making use of [`oxalica/rust-overlay`] in order to load the given rust-toolchain
- added weekly CI to keep `flake.lock` up to date
- I'd also volunteer to maintain the `flake.nix`
- updated `flake.lock` with `nix flake update`
@Toqozz 
[`flake-parts`]: https://flake.parts/
[`oxalica/rust-overlay`]: https://github.com/oxalica/rust-overlay

Improve flake

---

flake.nix

I forgot to add an `overlay` in my [previous PR](https://github.com/Toqozz/wired-notify/pull/123). This should add it back.

flake: add missing `overlay`

---

src/cli.rs

Solution to #112, where wired would panic without proper explanation after attempting to remove the existing socket with missing permissions.

Implemented proper error handling for socket removal

---

src/bus/dbus.rs
src/config.rs
src/main.rs
src/rendering/window.rs
wired.ron

Fixes #131 by changing behavior to:
- Use default for timeouts less than zero
- Never expire for timeouts equal to zero
- Use the timeout otherwise
I built and tested this locally (using `notify-send` and others), it works as expected
Also adds a new `timeout_behavior = {Legacy, DBusSpec}` config option, which defaults to the new behavior. The wiki should probably be updated after this lands as well.

Update timeout configuration to match spec

---

src/cli.rs

When `wired --action latest:default` is called, a Parse() error is logged, and the default action is not called. This is because "default" cannot be parsed as a `usize`.
I have fixed it in my local by simply setting the value to `0` whenever parsing fails; however, while this is the simplest solution, I suspect there may be better ways to solve this problem (I don't know rust at all).

Fix Parse() error

---

default.nix

Hello,
I have updated `default.nix`. Using `builtins.fetchGit ./.` would fail because the `.git` folder doesn't exist when fetched.
<details>
<summary>previous bad behaviour</summary>
```nix
nix-repl> wired-notify = import (fetchTarball "https://github.com/Toqozz/wired-notify/archive/1632418aa15889343028261663e81d8b5595860e.tar.gz")
nix-repl> wired-notify
fatal: '/nix/store/dvd85sj784iia3g8wjhpmng2k93gqm8c-source' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
warning: could not read HEAD ref from repo at 'file:///nix/store/dvd85sj784iia3g8wjhpmng2k93gqm8c-source', using 'master'
fatal: '/nix/store/dvd85sj784iia3g8wjhpmng2k93gqm8c-source' does not appear to be a git …
```

Fix flake-compat
